### ISSUE TITLE
Can i control background color before webpage loading done?

### ISSUE THREAD

**Issue by theolovesyou** [gree/unity-webview#241]
Hello.
Thanks for the good plugin.

Can i control background color before webpage loading done?
My game background color is black and webpage color is black.
The webview's default color is white. right?
While loading the page, webview's background color is shown .
so there is some flickering between start loading and finish loading.

Is there any solution for this?
Thanks again!

**Comment by KojiNakamaru** [comment]
You can specify `transparent: true` to make the webview transparent. The following example also shows how to modify the background color in `ld:` callback but it might be better to specify it in html/css.


```diff
--- a/sample/Assets/Scripts/SampleWebView.cs
+++ b/sample/Assets/Scripts/SampleWebView.cs
@@ -31,6 +31,7 @@ public class SampleWebView : MonoBehaviour
     {
         webViewObject = (new GameObject("WebViewObject")).AddComponent<WebViewObject>();
         webViewObject.Init(
+            transparent: true,
             cb: (msg) =>
             {
                 Debug.Log(string.Format("CallFromJS[{0}]", msg));
@@ -45,6 +46,9 @@ public class SampleWebView : MonoBehaviour
             },
             ld: (msg) =>
             {
+                webViewObject.EvaluateJS(@"
+                  document.body.style.background = 'gray';
+                ");
                 Debug.Log(string.Format("CallOnLoaded[{0}]", msg));
 #if !UNITY_ANDROID
                 // NOTE: depending on the situation, you might prefer
```

**Comment by theolovesyou** [comment]
Thanks for quick reply!
It works like a charm.

**Comment by lutfianasari** [comment]
Sorry for asking in this thread because I have the same problem as this one.
I tried the above solution, and the webview became transparent.
But, the next part:
```
+                webViewObject.EvaluateJS(@"
+                  document.body.style.background = 'gray';
+                ");
```
didn't seem working. It showed 'gray' in the above part of the page, and the webview remained transparent.
After making the webview transparent, can we make the transparent value into false again?

**Comment by KojiNakamaru** [comment]
Sorry, I've fixed the issue in #315 and updated binaries. Could you please try the latest?

**Comment by lutfianasari** [comment]
Thank you very much as always. It's now working :+1: 
I think the issue can be closed.

**Comment by KojiNakamaru** [comment]
Thank you for confirmation!

**Comment by jt7785** [comment]
I'm still facing a white screen before load.
Setting transparent, or changing the color to red didn't help.
Do you have any thoughts?

**Comment by KojiNakamaru** [comment]
At least the sample app shows nothing initially and then a transparent page with the following diff:

```diff
diff --git a/sample/Assets/Scripts/SampleWebView.cs b/sample/Assets/Scripts/SampleWebView.cs
index e8aa466..b2a8cdf 100644
--- a/sample/Assets/Scripts/SampleWebView.cs
+++ b/sample/Assets/Scripts/SampleWebView.cs
@@ -35,6 +35,7 @@ public class SampleWebView : MonoBehaviour
     {
         webViewObject = (new GameObject("WebViewObject")).AddComponent<WebViewObject>();
         webViewObject.Init(
+            transparent: true,
             cb: (msg) =>
             {
                 Debug.Log(string.Format("CallFromJS[{0}]", msg));
diff --git a/sample/Assets/StreamingAssets/sample.html b/sample/Assets/StreamingAssets/sample.html
index 38de86b..8e71074 100644
--- a/sample/Assets/StreamingAssets/sample.html
+++ b/sample/Assets/StreamingAssets/sample.html
@@ -2,7 +2,7 @@
   <head>
     <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
     <title>Unity WebView</title>
-    <script src="sample.js"></script>
+    <!-- <script src="sample.js"></script> -->
     <!-- geolocation example
     <script>
       window.addEventListener(
@@ -17,7 +17,7 @@
     </script>
     -->
   </head>
-  <body>
+  <body style="background-color: transparent">
     <h1>Hello Unity WebView!</h1>
     <hr/>
     <!-- geolocation example
```
