### ISSUE TITLE
Videos in ios devices

### ISSUE THREAD

**Issue by Vansito94** [gree/unity-webview#347]
When showing videos in android they start playing automatically but in IOS you have to press in the play button and it starts playing in a different view. How can I play the video automatically like in android.
![img_3310](https://user-images.githubusercontent.com/42741617/44662551-6543b400-aa0e-11e8-9f2a-2cd2ead9d701.PNG)

**Comment by KojiNakamaru** [comment]
I've fixed to allow the inline media play back in #348. A video can now be automatically played by adequately setting attributes for the video tag as below:
```html
<video autoplay muted playsinline><source src="sample.mp4"></video>
```
cf. https://www.thomasvisser.me/2018/06/26/wkwebview-media/

**Comment by francois-n-dream** [comment]
Not for iOS, but our game runs on an AndroidTV and is controlled remotely. We added:

```
 // CWebViewPlugin.java (Around line 250)
  webSettings.setMediaPlaybackRequiresUserGesture(false);
```

and build the .jar file ourself.

Videos now autoplay also unmuted.

**Comment by Vansito94** [comment]
Just uploaded unity to version 2018.2.5 and also 2018.2.6 and in none of them is working the video in the webview on ios devices, only shows the first frame of the video you try to reproduce... but thats it, there is no even a play button, it's like an simple image. It works perfectly in android devices.

**Comment by KojiNakamaru** [comment]
Hmm, at least with the following diff (and sample.mp4 under StreamingAssets), the sample app works successfully with 2018.2.6f1.
```diff
diff --git a/sample/Assets/Scripts/SampleWebView.cs b/sample/Assets/Scripts/SampleWebView.cs
index 1d169a1..5594cd7 100644
--- a/sample/Assets/Scripts/SampleWebView.cs
+++ b/sample/Assets/Scripts/SampleWebView.cs
@@ -109,6 +109,7 @@ public class SampleWebView : MonoBehaviour
             var exts = new string[]{
                 ".jpg",
                 ".js",
+                ".mp4",
                 ".html"  // should be last
             };
             foreach (var ext in exts) {
diff --git a/sample/Assets/StreamingAssets/sample.html b/sample/Assets/StreamingAssets/sample.html
index 0962587..07a301e 100644
--- a/sample/Assets/StreamingAssets/sample.html
+++ b/sample/Assets/StreamingAssets/sample.html
@@ -7,6 +7,9 @@
   <body>
     <h1>Hello Unity WebView!</h1>
     <hr/>
+    <video width="320" height="240" autoplay playsinline muted>
+      <source src="sample.mp4" type="video/mp4">
+    </video>
     <p id="msg">()</p>
     <p><a href="https://google.com">https://google.com</a> (for testing go/back buttons)</p>
     <p><a href="http://httpbin.org/headers">http://httpbin.org/headers</a> (for testing custom headers.)</p>
```

**Comment by Vansito94** [comment]
XCode Version: 9.4.1
Unity Version: 2018.2.6f1

Still not working on ios and I can't understand why. The problem is the same. The webview only shows the first frame of the video but is not playing. I tested with several mp4 video but none of them seem to work.

I downloaded one of the mp4 sample videos from: http://techslides.com/demos/sample-videos/small.mp4

![0](https://user-images.githubusercontent.com/42741617/44993844-4f009f80-af9c-11e8-8b51-c62b2e0c397b.png)
![1](https://user-images.githubusercontent.com/42741617/44993848-5162f980-af9c-11e8-95ec-fde4391986ee.png)
![2](https://user-images.githubusercontent.com/42741617/44993850-53c55380-af9c-11e8-8386-a1357fa23229.png)
![3](https://user-images.githubusercontent.com/42741617/44993853-5627ad80-af9c-11e8-87db-1f682c4e6143.PNG)

The project "Assets" folder is also attatched:

[Assets.zip](https://github.com/gree/unity-webview/files/2346011/Assets.zip)

**Comment by KojiNakamaru** [comment]
WebView.mm in your Assets.zip is old. You might pull the latest repository but haven't you imported the latest package?

**Comment by KojiNakamaru** [comment]
BTW, I've now included @francois-n-dream's modification for Android and also adjusted WebView.mm so that it surely works for any media and for UIWebView in #353. Could you please try the latest.

**Comment by Vansito94** [comment]
I have tried the new package and it works PERFECTLY. 

If you ever travel to Valencia, Spain. Just let me know and I'll invite you to a paella! Thank you very much for your dedication.

**Comment by KojiNakamaru** [comment]
Welcome and thanks:-).
