### ISSUE TITLE
Unity.call function does not survive on iOS and OS X, multiple page loads on like login

### ISSUE THREAD

**Issue by sm-j** [gree/unity-webview#390]
Hi,

I have used this code and works perfect in android.
With unity i have developed a app where user can add login details in web-view and then redirected to success page where i have added unity.call in web-page code.
As mentioned earlier it works fine in android but in iOS i am not receiving message from Unity.call.

Here is my iOS device information:
My Device Information:
Device: iPhone11,2
iOS Version: 12.1.2
Language: en-US (English (United States))
Carrier: Verizon
Timezone: EST
Architecture: N/A
Connection Status: WiFi
Paired Apple Watch: N/A

And my unity version is 5.6.1f1.

Any suggestion for the issue?

Thanks

**Comment by KojiNakamaru** [comment]
If you own target html pages and can edit them, you can simply add those pages the following part,

https://github.com/gree/unity-webview/blob/master/sample/Assets/Scripts/SampleWebView.cs#L59-L71

thus,

```html
<script>
  if (window.navigator.userAgent.toLowerCase().indexOf("safari") {
    if (window && window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.unityControl) {
      window.Unity = {
        call: function(msg) {
          window.webkit.messageHandlers.unityControl.postMessage(msg);
        }
      }
    } else {
      window.Unity = {
        call: function(msg) {
          window.location = 'unity:' + msg;
        }
      }
    }
  }
</script>
```

Also if you only utilize WKWebView (it is enabled if you specifcy `enableWKWebView: true` and the target iOS platform has WKWebView), you may directly utilize `window.webkit.messageHandlers.unityControl.postMessage(msg)` which is predefined without any script injection/definition.

As you might already refer, one of other approaches is to inject the definition in `update()` (cf. https://github.com/gree/unity-webview/issues/107#issuecomment-239722830 ).

**Comment by KojiNakamaru** [comment]
Which one did you try? I've just found an error in the code above (sorry), so here is corrected one:
```html
<script>
  if (window.navigator.userAgent.toLowerCase().indexOf("safari")) {
    if (window && window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.unityControl) {
      window.Unity = {
        call: function(msg) {
          window.webkit.messageHandlers.unityControl.postMessage(msg);
        }
      }
    } else {
      window.Unity = {
        call: function(msg) {
          window.location = 'unity:' + msg;
        }
      }
    }
  }
</script>
```
The difference is the following:
```diff
--- t.html.orig	2019-01-28 22:38:51.000000000 +0900
+++ t.html	2019-01-28 22:39:56.000000000 +0900
@@ -1,5 +1,5 @@
 <script>
-  if (window.navigator.userAgent.toLowerCase().indexOf("safari") {
+  if (window.navigator.userAgent.toLowerCase().indexOf("safari")) {
     if (window && window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.unityControl) {
       window.Unity = {
         call: function(msg) {
```

**Comment by sm-j** [comment]
Here is my code, 
Am i making any mistake?

`<html>
	<head>
		<META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">
		<title> OB Auth | Success </title>
		<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
		<script type="text/javascript">
			$(document).ready(function(e)
			{
				Unity.call (“This is test message“);
			});
		</script>
		<script>
			if (window.navigator.userAgent.toLowerCase().indexOf("safari") != -1)
			{
	             		if (window && window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.unityControl)
		            	{
					window.Unity = 
					{
                    				call: function(msg) 
						{
							window.webkit.messageHandlers.unityControl.postMessage(msg);
		                          	}
	                     	}
                		}
                 		else
                 		{
		                 	window.Unity = 
					{
		                        	call: function(msg) 
						{
			                           window.location = 'unity:' + msg;
                      			}
                    			}
                		}
           		}
		</script>
	</head>
	<body>
		<p style="font-size:20px;color:#5C5C5C;"><strong><label>Testing</label></strong></p>
	</body>
</html>`

**Comment by KojiNakamaru** [comment]
Ah, sorry, we should use "iphone" instead of "safari" for *WebView. So your test html file should be the following:
```html
<html>
<head>
	<title> OB Auth | Success </title>
	<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
	<script type="text/javascript">
		$(document).ready(function(e)
		{
			Unity.call("This is test message");
		});
	</script>
	<script>
		if (window.navigator.userAgent.toLowerCase().indexOf("iphone") != -1)
		{
             		if (window && window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.unityControl)
	            	{
				window.Unity = 
				{
                			call: function(msg) 
					{
					    window.webkit.messageHandlers.unityControl.postMessage(msg);
	                          	}
                     	        }
            		}
             		else
             		{
	                 	window.Unity = 
				{
	                        	call: function(msg) 
					{
		                           window.location = 'unity:' + msg;
                  			}
                		}
            		}
       		}
	</script>
</head>
<body>
	<p style="font-size:20px;color:#5C5C5C;"><strong><label>Testing</label></strong></p>
</body>
</html>
```

**Comment by sm-j** [comment]
That's okay.
Trying that.

**Comment by sm-j** [comment]
Still getting following error

![screen shot 2019-01-29 at 3 43 33 pm](https://user-images.githubusercontent.com/22738614/51901054-c5cf8680-23dc-11e9-87c8-746133da190b.png)

**Comment by KojiNakamaru** [comment]
You cannot run it on OSX, as the code checks whether it runs on iOS or not and defines `Unity.call()` only for iOS.

**Comment by KojiNakamaru** [comment]
It should work well both on iOS simulator and on real device. The following is a bit modified one (so that we can see the test message more easily) I've tested it with the sample app,

```html
<html>
<head>
	<title> OB Auth | Success </title>
	<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
	<script type="text/javascript">
		$(document).ready(function(e)
		{
                    setTimeout(function() {
			Unity.call("This is test message");
                    }, 3000);
		});
	</script>
	<script>
		if (window.navigator.userAgent.toLowerCase().indexOf("iphone") != -1)
		{
             		if (window && window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.unityControl)
	            	{
				window.Unity = 
				{
                			call: function(msg) 
					{
					    window.webkit.messageHandlers.unityControl.postMessage(msg);
	                          	}
                     	        }
            		}
             		else
             		{
	                 	window.Unity = 
				{
	                        	call: function(msg) 
					{
		                           window.location = 'unity:' + msg;
                  			}
                		}
            		}
       		}
	</script>
</head>
<body>
	<p style="font-size:20px;color:#5C5C5C;"><strong><label>Testing</label></strong></p>
</body>
</html>
```

and it shows the following on iOS simulator.

![image](https://user-images.githubusercontent.com/2645978/52028121-2b448400-2551-11e9-9b0d-682ea286184b.png)

Please also note the followings:

* You should remove the injection code ( https://github.com/gree/unity-webview/blob/a854c8a74a8a5a6b01acffa9c0d718a2ab96f86e/sample/Assets/Scripts/SampleWebView.cs#L54-L94 ), as you define `Unity.call()` in html.

* In your original code ( https://github.com/gree/unity-webview/issues/390#issuecomment-458425534 ), `Unity.call()`'s argument contains incorrect double quotes.

**Comment by sm-j** [comment]
Thanks, i will make these changes.
