### ISSUE TITLE
Cannot build to Apple silicon

### ISSUE THREAD

**Issue by t-b-benedek-99** [gree/unity-webview#828]
We cannot build to Mac with the Architecture in the Build Settings being set to "Intel 64-bit + Apple silicon", nor to "Apple silicon".
A dll is missing for this. Actually, we think the problem may derive from the fact that in the native code for the Mac plugin the Xcode target is: 10.13. Could you help us with this issue? And probably you should raise it so that Apple silicon should be supported.
![issue](https://user-images.githubusercontent.com/48593728/182378511-f02a1112-6357-4aeb-ad85-982e8c3da351.png)

**Comment by KojiNakamaru** [comment]
Thank you for the report. WebView.bundle includes m1 binary since #761, but I should also fixed WebView.bundle.meta. I fixed it in #829 and updated binaries. Could you please try the latest?

**Comment by t-b-benedek-99** [comment]
Thank you very much for the quick help! Yes, now it is working perfectly.

Just one note: we tried on a newer Unity version as well (because we're planning to update our project in the future), so we tried specifically on 2021.3.6f1 and there the issue is still present if the target architecture is Apple silicon. I don't know if I should create a new task about this or if you can deal with it in this same ticket. What do you prefer?

**Comment by KojiNakamaru** [comment]
The latest plugin seems to work okay with 2021.3.6f1. I adjusted the sample app to be opened directly and built with 2021.3.6f1 on https://github.com/gree/unity-webview/tree/example-for-828 .  Could you please try it?

**Comment by nketkar** [comment]
@KojiNakamaru I am running into the same DLLErrorNotFoundException described above using Unity 2021.3.12f1. 

Sample Scene builds fine when set to Intel 64-bit. Is there a fix that can be merged for all 2021 versions? Our aim to build with "Intel 64-bit + Apple silicon" architecture

**Comment by KojiNakamaru** [comment]
Hmm, I built https://github.com/gree/unity-webview/tree/example-for-828/sample with Unity 2021.3.12f1 and it run on both intel/apple silicon machines. Please try to download
[sample-osx-fat-binary.txt](https://github.com/gree/unity-webview/files/10575636/sample-osx-fat-binary.txt), rename to sample-osx-fat-binary.txz, and open. Extracted sample-osx-fat-binary.app run on my test machines:

* Mac Studio (2022, Apple M1 Ultra)/Ventura 13.2
* MacBook Pro (15-inch, 2019, Intel Core i7)/Ventura 13.2

**Comment by nketkar** [comment]
Oh my mistake, I had just copied over the sample app and not the binaries as well. Everything works as expected! Thank you @KojiNakamaru
